# for dev/master branch
-
  version: 1.0.0.{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - dev
    - master
  skip_tags: true
  image: Visual Studio 2015
  configuration: Debug
  platform: Any CPU
  build_script:
  - cmd: tools\nuget restore Azure.Insights.WebTests.Sdk.sln
  - cmd: msbuild Azure.Insights.WebTests.Sdk.sln /t:ReBuild /v:minimal /p:Configuration=Debug;TargetFrameworkVersion=v4.5;DefineConstants="DEBUG;TRACE";OutPutPath=bin\Debug\net45
  test_script:
  - cmd: tools\nuget restore Azure.Insights.WebTests.Sdk.sln
  - cmd: msbuild Azure.Insights.WebTests.Sdk.sln /t:ReBuild /v:minimal /p:Configuration=Debug;TargetFrameworkVersion=v4.5;DefineConstants="DEBUG;TRACE";OutPutPath=bin\Debug\net45
  - ps: .\run-tests.ps1 -Configuration Debug

# for release/all branch
-
  version: 1.0.0.{build}-preview
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - release/all
  skip_tags: true
  image: Visual Studio 2015
  configuration: Release
  platform: Any CPU
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    github_auth_token:
      secure: 3tp7rCl4cvk/WDYBaeodIlmalNiYVWQYxE1wmVU7aMbkMKP0WtlMjjOU2yhX0D4n
  build_script:
  - cmd: tools\nuget restore Azure.Insights.WebTests.Sdk.sln
  - cmd: msbuild Azure.Insights.WebTests.Sdk.sln /t:ReBuild /v:minimal /p:Configuration=Release;TargetFrameworkVersion=v4.5;DefineConstants="TRACE";OutPutPath=bin\Release\net45\
  test_script:
  - cmd: tools\nuget restore Azure.Insights.WebTests.Sdk.sln
  - cmd: msbuild Azure.Insights.WebTests.Sdk.sln /t:ReBuild /v:minimal /p:Configuration=Release;TargetFrameworkVersion=v4.5;DefineConstants="TRACE";OutPutPath=bin\Release\net45\
  - ps: .\run-tests.ps1 -Configuration Release
  after_test:
  - ps: .\build-package.ps1 -Version %APPVEYOR_BUILD_VERSION%
  artifacts:
  - path: '**\Aliencube.Azure.Insights.WebTests.Services.*.nupkg'
    name: Insights.WebTests.Services
  deploy:
  - provider: NuGet
    api_key:
      secure: ZdI7BA2YRQg/yRMPbRGTTJeGWj3X3o8kNhf4LeA5YkV072GpmKwQ3aW+KVgMbkZX
    artifact: Insights.WebTests.Services
    on:
      branch: release/all
      platform: Any CPU
      configuration: Release
  after_deploy:
  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_auth_token):x-oauth-basic@github.com`n"
  - cmd: git push origin --delete release/all
